=== Nando-Cardoso/Password-Tester/PasswordTester/bin/Debug/netcoreapp3.1/accounts_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for the PasswordTester Program",

  "type": "object",
  "required": [ "Description", "UserId", "Password" ],
  "properties": {
    "Description": {
      "type": "string",
      "description": "A description of the online account"
    },
    "UserId": {
      "type": "string",
      "description": "User's identifier for logging-in"
    },
    "LoginUrl": {
      "type": "string",
      "description": "Web address of the account's log-in page",
        "format": "uri"
    },
    "AccountNum": {
      "type": "string",
      "description": "The account number for the user's online account"
    },
    "Password": {
      "description": "Information related specifically to the password",
      "type": "object",
      "required": [ "Value", "StrengthNum", "StrengthText" ],
      "properties": {
        "Value": {
          "type": "string",
          "description": "User's password for logging-in"
        },
        "StrengthNum": {
          "type": "number",
          "description": "Indicates how secure the password is",
          "minimum": 0,
          "maximum": 100
        },
        "StrengthText": {
          "type": "string",
          "description": "Indicates how secure the password is",
          "enum": [
            "very weak",
            "weak",
            "good",
            "strong",
            "very strong"
          ]
        },
        "LastReset": {
          "type": "string",
          "description": "date the password was last updated"
        }
      }
    }
  },
  "additionalProperties": false
}

=== Nando-Cardoso/Password-Tester/PasswordTester/bin/Release/netcoreapp3.1/accounts_data.json
[{"Description":"Fernando","UserId":"asd123","LoginUrl":"https://www.google.com/","AccountNum":"1234","Password":{"Value":"testPassword","StrengthNum":41,"StrengthText":"good","LastReset":"6/6/2020"}},{"Description":"Thales","UserId":"thalesTest","LoginUrl":"https://www.google.com/","AccountNum":"312456","Password":{"Value":"testpassword1.1","StrengthNum":99,"StrengthText":"very strong","LastReset":"6/2/2020"}},{"Description":"Fanshawe","UserId":"f_cardoso","LoginUrl":"https://www.google.com/","AccountNum":"","Password":{"Value":"fanshaweTestPassword1.0","StrengthNum":100,"StrengthText":"very strong","LastReset":"6/2/2020"}}]
